### ISSUE TITLE
Not working with ruby 2.3.1

### ISSUE THREAD

**Issue by lichtamberg** [MyceliumGear/straight-server#67]
Tried to make it work with ruby 2.3.1..

gem install worked, but afterwards when I want to start the server for the first time, this bug occures:

```shell
> gem install straight-server
Fetching: satoshi-unit-0.1.8.gem (100%)
Successfully installed satoshi-unit-0.1.8
Fetching: multi_xml-0.5.5.gem (100%)
Successfully installed multi_xml-0.5.5
Fetching: httparty-0.13.7.gem (100%)
When you HTTParty, you must party hard!
Successfully installed httparty-0.13.7
Fetching: btcruby-1.6.gem (100%)
Successfully installed btcruby-1.6
Fetching: straight-1.0.0.gem (100%)
Successfully installed straight-1.0.0
Fetching: sequel-4.34.0.gem (100%)
Successfully installed sequel-4.34.0
Fetching: ruby-hmac-0.4.0.gem (100%)
Successfully installed ruby-hmac-0.4.0
Fetching: pony-1.11.gem (100%)
Successfully installed pony-1.11
Fetching: logmaster-0.1.5.gem (100%)
Successfully installed logmaster-0.1.5
Fetching: rack-accept-media-types-0.9.gem (100%)
Successfully installed rack-accept-media-types-0.9
Fetching: rack-respond_to-0.9.8.gem (100%)
Successfully installed rack-respond_to-0.9.8
Fetching: git-version-bump-0.15.1.gem (100%)
Successfully installed git-version-bump-0.15.1
Fetching: rack-contrib-1.4.0.gem (100%)
Successfully installed rack-contrib-1.4.0
Fetching: log4r-1.1.10.gem (100%)
Successfully installed log4r-1.1.10
Fetching: http_parser.rb-0.6.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed http_parser.rb-0.6.0
Fetching: em-websocket-0.3.8.gem (100%)
Successfully installed em-websocket-0.3.8
Fetching: em-synchrony-1.0.5.gem (100%)
Successfully installed em-synchrony-1.0.5
Fetching: async-rack-0.5.1.gem (100%)
Successfully installed async-rack-0.5.1
Fetching: goliath-1.0.4.gem (100%)
Successfully installed goliath-1.0.4
Fetching: faye-websocket-0.10.3.gem (100%)
Successfully installed faye-websocket-0.10.3
Fetching: straight-server-1.0.0.gem (100%)
Successfully installed straight-server-1.0.0
21 gems installed
> straight-server
/Users/myuser/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fee00c3ccf0 goliath-1.0.4> (NoMethodError)
  from /Users/myuser/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
  from /Users/myuser/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
  from /Users/myuser/.rvm/gems/ruby-2.3.1/gems/straight-server-1.0.0/bin/straight-server:3:in `<top (required)>'
  from /Users/myuser/.rvm/gems/ruby-2.3.1/bin/straight-server:23:in `load'
  from /Users/myuser/.rvm/gems/ruby-2.3.1/bin/straight-server:23:in `<main>'
  from /Users/myuser/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
  from /Users/myuser/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
``

**Comment by lichtamberg** [comment]
My fault, had an "old" version of rubygems installed.. This fixed it:

```shell
> gem update --system
> gem install rubygems-update
> update_rubygems
=> RubyGems 2.6.4 installed
> gem --version
=> 2.6.4
# works!
```
