### ISSUE TITLE
straight-server is not working

### ISSUE THREAD

**Issue by saaiful** [MyceliumGear/straight-server#79]
after using 'straight-server -p 9696'command  I'm getting following error:
```
Pending migrations for the database detected. Migrating.../usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:931:in `type_literal_generic': Unsupported ruby class used as database type: Bignum (Sequel::Error)
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:916:in `type_literal'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:544:in `column_definition_sql'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:452:in `alter_table_add_column_sql'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:445:in `alter_table_op_sql'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:496:in `alter_table_sql'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/adapters/shared/sqlite.rb:265:in `alter_table_sql'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:526:in `block in alter_table_sql_list'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:526:in `map'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:526:in `alter_table_sql_list'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/adapters/shared/sqlite.rb:246:in `block (2 levels) in apply_alter_table'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/adapters/shared/sqlite.rb:246:in `each'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/adapters/shared/sqlite.rb:246:in `block in apply_alter_table'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:215:in `_transaction'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:190:in `block in transaction'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:156:in `transaction'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/adapters/shared/sqlite.rb:238:in `apply_alter_table'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:433:in `apply_alter_table_generator'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:81:in `alter_table'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:39:in `add_column'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/straight-server-1.0.0/db/migrations/015_add_amount_paid_to_orders.rb:4:in `block (2 levels) in <top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:106:in `instance_eval'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:106:in `apply'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:560:in `block (2 levels) in run'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:476:in `checked_transaction'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:559:in `block in run'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:556:in `each'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:556:in `run'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:401:in `run'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:110:in `run_migrations'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:43:in `prepare'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/straight-server-1.0.0/lib/straight-server/server.rb:10:in `initialize'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/goliath-1.0.4/lib/goliath/application.rb:105:in `new'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/goliath-1.0.4/lib/goliath/application.rb:105:in `run!'
        from /usr/local/rvm/gems/ruby-2.1.8/gems/goliath-1.0.4/lib/goliath/application.rb:133:in `block in <module:Goliath>'
```

What to do ?

**Comment by saaiful** [comment]
Changing Bignum Into Float Solved this issue.
