### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ultrafunkamsterdam** [MyceliumGear/straight-server#86]
Hi man,

This is not really an issue, but more a question which i don't know how to deliver to you other ways.
First off: great project. It works great and is understandable for less novice players in the bitcoin game.
I have some issues with the exchange adapters.

When i create an order, for ex:

`curl -X POST -F 'amount=10' -F 'currency=EUR' http://localhost:9000/gateways/1/orders?`

or using it from the website using a php curl request like so:

```
 $ch = curl_init('https://servername.tld:9000/gateways/1/orders?');
    curl_setopt_array($ch, array(
        CURLOPT_POST => TRUE,
        CURLOPT_RETURNTRANSFER => TRUE,
        CURLOPT_HTTPHEADER => array('Content-Type: application/json'),
        CURLOPT_POSTFIELDS => json_encode( ["amount" => $_POST['amount'], "currency" => "EUR" ] )
    ));
$response = curl_exec($ch);
if($response === FALSE){
    die(curl_error($ch));
}
echo $response;
}
```

I'm getting error as follows:

```
I, [2017-08-06T14:16:56.166006 #15934]  INFO -- : POST /gateways/1/orders
{"amount"=>"10", "currency"=>"EUR"}
I, [2017-08-06T14:16:56.166257 #15934]  INFO -- : Creating new order with attrs: {:amount=>"10", :currency=>"EUR", :btc_denomination=>nil, :keychain_id=>nil, :callback_data=>nil, :data=>nil, :description=>nil}
F, [2017-08-06T14:16:56.331672 #15934] FATAL -- : Satoshi::TooManyDigitsAfterDecimalPoint: Too many digits (17) after decimal point used for btc value, while 8 allowed
Backtrace:
    /usr/local/rvm/gems/ruby-2.4.0/gems/satoshi-unit-0.2.2/lib/satoshi.rb:147:in `convert_to_satoshi'
    /usr/local/rvm/gems/ruby-2.4.0/gems/satoshi-unit-0.2.2/lib/satoshi.rb:24:in `initialize'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-1.0.0/lib/straight/exchange_rate_adapter.rb:17:in `new'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-1.0.0/lib/straight/exchange_rate_adapter.rb:17:in `convert_from_currency'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-1.0.0/lib/straight/gateway.rb:158:in `block in amount_from_exchange_rate'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-1.0.0/lib/straight/gateway.rb:193:in `block in try_adapters'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-1.0.0/lib/straight/gateway.rb:191:in `each'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-1.0.0/lib/straight/gateway.rb:191:in `try_adapters'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-1.0.0/lib/straight/gateway.rb:157:in `amount_from_exchange_rate'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-1.0.0/lib/straight/gateway.rb:99:in `new_order'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-server-1.0.0/lib/straight-server/gateway.rb:140:in `create_order'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:55:in `create'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:169:in `dispatch'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-server-1.0.0/lib/straight-server/orders_controller.rb:16:in `initialize'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:133:in `new'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:133:in `block in initialize_routes'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-server-1.0.0/lib/straight-server/server.rb:71:in `block in process_request'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-server-1.0.0/lib/straight-server/server.rb:70:in `each'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-server-1.0.0/lib/straight-server/server.rb:70:in `process_request'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-server-1.0.0/lib/straight-server/server.rb:43:in `block in response'
    /usr/local/rvm/gems/ruby-2.4.0/gems/logmaster-0.1.5/lib/logmaster.rb:54:in `watch_exceptions'
    /usr/local/rvm/gems/ruby-2.4.0/gems/straight-server-1.0.0/lib/straight-server/server.rb:36:in `response'
    /usr/local/rvm/gems/ruby-2.4.0/gems/goliath-1.0.5/lib/goliath/api.rb:163:in `call'
    /usr/local/rvm/gems/ruby-2.4.0/gems/faye-websocket-0.10.7/lib/faye/adapters/goliath.rb:28:in `call'
    /usr/local/rvm/gems/ruby-2.4.0/gems/goliath-1.0.5/lib/goliath/rack/params.rb:67:in `call'
    /usr/local/rvm/gems/ruby-2.4.0/gems/goliath-1.0.5/lib/goliath/rack/async_middleware.rb:73:in `call'
    /usr/local/rvm/gems/ruby-2.4.0/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
    /usr/local/rvm/gems/ruby-2.4.0/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:114:in `call'
    /usr/local/rvm/gems/ruby-2.4.0/gems/async-rack-0.5.1/lib/async_rack/async_callback.rb:91:in `block in new'
    /usr/local/rvm/gems/ruby-2.4.0/gems/rack-1.6.8/lib/rack/reloader.rb:45:in `call'
    /usr/local/rvm/gems/ruby-2.4.0/gems/goliath-1.0.5/lib/goliath/request.rb:166:in `block in process'

```

I did not touch the exchange adapters in any way, so probably i should set things up, but i don't know how. 

Sorry for submitting this as an issue, it could be immideately closed hereafter.

Kind regards

**Comment by ultrafunkamsterdam** [comment]
My config is as follows:
```
default:
    pubkey: xpub************ 
    confirmations_required: 0
    order_class: "StraightServer::Order"
    secret: 'secret'
    check_signature: false
    callback_url: 'https://website.tld/api/pay'
    default_currency: 'BTC'
    orders_expiration_period: 600 # seconds
    address_provider: 'Bip32'
    address_derivation_scheme: 'm/0/n'

    # This options decides whether we should also check the DB for status updates first
    # when we check order status. That is, if we're tracking an order and this option
    # is set to true, it first fetches the fields from the local DB, sees if the status has changed there,
    # and if it did - we no longer need to query the blockchain.
    #
    # Usecase? Currently mostly debugging (so set it to false for production). For example,
    # when testing payments, you don't actually want to pay, you can just run the server console,
    # change order status in the DB and see how your client picks it up, showing you that your
    # order has been paid for.
    check_order_status_in_db_first: true # Consider changing to `false` in production.

    # The order matters here, we check for prices with the first adapter,
    # if it fails, move on to the next
    exchange_rate_adapters:
      - Bitpay
      - Coinbase
      - Bitstamp

    # This affects whether it is possible to create a new order with the gateway.
    # If it's set to false, then it won't be possible to create a new order, but
    # it will keep checking on the existing ones.
    active: true
    # If this option set to true, gateway using TESTNET
    test_mode: false
```

**Comment by AlexanderPavlenko** [comment]
> satoshi-unit-0.2.2

Pinpointing it to `0.1.8` in the Gemfile may help.

**Comment by ultrafunkamsterdam** [comment]
Will give that a try. thank you!
