### ISSUE TITLE
Invalid filter expression

### ISSUE THREAD

**Issue by mahla-chr** [MyceliumGear/straight-server#93]
hi,
would you please help me to solve this error:

```
~/straight-server-master$ straight-server -p 9696
/home/user1/.rvm/gems/ruby-2.4.1/gems/straight-1.0.0/lib/straight/faraday_monkeypatch.rb:1: warning: already initialized constant Faraday::SSLOptions
/home/user1/.rvm/gems/ruby-2.4.1/gems/faraday-0.15.2/lib/faraday/options.rb:218: warning: previous definition of SSLOptions was here
Setting config dir to /home/user1/.straight
I, [2018-06-11T16:02:32.114065 #114567]  INFO -- : starting Straight Server v 1.0.0
/home/user1/.rvm/gems/ruby-2.4.1/gems/sequel-5.9.0/lib/sequel/dataset/query.rb:1282:in `filter_expr': Invalid filter expression: "status < 2" (Sequel::Error)
	from /home/user1/.rvm/gems/ruby-2.4.1/gems/sequel-5.9.0/lib/sequel/dataset/query.rb:1243:in `add_filter'
	from /home/user1/.rvm/gems/ruby-2.4.1/gems/sequel-5.9.0/lib/sequel/dataset/query.rb:1044:in `where'
	from /home/user1/.rvm/gems/ruby-2.4.1/gems/sequel-5.9.0/lib/sequel/model/plugins.rb:33:in `where'
	from /home/user1/.rvm/gems/ruby-2.4.1/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:170:in `resume_tracking_active_orders!'
	from /home/user1/.rvm/gems/ruby-2.4.1/gems/straight-server-1.0.0/lib/straight-server/server.rb:15:in `initialize'
	from /home/user1/.rvm/gems/ruby-2.4.1/gems/goliath-1.0.6/lib/goliath/application.rb:105:in `new'
	from /home/user1/.rvm/gems/ruby-2.4.1/gems/goliath-1.0.6/lib/goliath/application.rb:105:in `run!'
	from /home/user1/.rvm/gems/ruby-2.4.1/gems/goliath-1.0.6/lib/goliath/application.rb:133:in `block in <module:Goliath>'

```
Os : ubuntu 16.04
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
gem version: 2.6.11

**Comment by gabiruiz91** [comment]
In the file located at /home/user1/.rvm/gems/ruby-2.4.1/gems/straight-server-1.0.0/lib/straight-server/initializer.rb:170

change the line 170 

**StraightServer::Order.where("status <2").each do |order|**

for

**StraightServer::Order.where(status: 0...2).each do |order|**

**Comment by AlexanderPavlenko** [comment]
Hello! In case this is still an issue, feel free to submit it to https://github.com/mycelium-com/gear-engine/issues
